### PR TITLE
Support Python 2 & Add unit tests for MultiFS support

### PR DESCRIPTION
**Pull request by chfw**
`is_file()` demands utf-8 string, which is not always guaranteed by python 2.

python 2 test failed. I will split this PR and deliver a PR to support python 2.7.

https://travis-ci.org/moremoban/moban/jobs/567662254

### CODE REVIEW

**Comment by althonos** [comment]
I still don't think this is needed because it can be done with `fs.multifs.MultfiFS` already. Let me give you an example that suits your usecase:
```python
import fs
import fs.multifs
import jinja2_fsloader

templates = fs.multifs.MultiFS()
templates.add_fs("s3://mybucket")
templates.add_fs("file://my/templates/folder")
templates.add_fs("zip://templates.zip")

loader = jinja2_fsloader.FSLoader(templates)
```

Doing so means the loader will be able to look in the 3 locations at once. If several files are named the same (i.e. there is `/template/a.html` in both the ZIP and the S3, the ZIP template will have prioirty because it was added later).

**Comment by chfw** [comment]
It took me a few days to learn your tip! 

The following modified example worked out of the box. so Thanks for your tip.

```
import fs
import fs.multifs
import jinja2_fsloader

templates = fs.multifs.MultiFS()
templates.add_fs("s3://mybucket", fs.open_fs("s3://mybucket"))
templates.add_fs("file://my/templates/folder", fs.open_fs("file://my/templates/folder"))
templates.add_fs("zip://templates.zip", fs.open_fs("zip://templates.zip"))

loader = jinja2_fsloader.FSLoader(templates)
```

**Comment by chfw** [comment]
python 2 test failed. I will split this PR and deliver a PR to support python 2.7.

https://travis-ci.org/moremoban/moban/jobs/567662254

**Comment by chfw** [comment]
@althonos , please give a second look.

**Comment by althonos** [comment]
Thank you!

**Comment by chfw** [comment]
Thanks. It is team work.

**Comment by althonos** [comment]
Release `v0.2.0` is up.

**Pull request merged**
